apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
      - name: node-api
        image: shruti29044/node-k8s-api:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-api-api
spec:
  selector:
    app: node-api
  ports:
  - port: 3000
    targetPort: 3000
    name: http
