name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps & test
        run: |
          cd app
          npm install
          npm test

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: your_dockerhub/your-image:latest
          format: 'table'

      - name: Docker Build & Push
        run: |
          docker build -t your_dockerhub/your-image:latest ./app
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push your_dockerhub/your-image:latest

      - name: Deploy to K8s
        run: |
          helm upgrade --install node-api ./helm/node-api-chart --set image.tag=latest
